# Bevy's "fast compile times" recommended setup from:
# https://bevyengine.org/learn/book/getting-started/setup/
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]
